# https://shapesecurity.github.io/salvation/index.html
name: Build and Deploy Demo Site
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
    - name: Install and Build 🔧 
      working-directory: ./docs
      run: |
        npm install
        npm run build
    - name: Deploy 🚀
      if: |
        !cancelled() && !failure()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/public
